### ISSUE TITLE
Support BRAT installation

### ISSUE THREAD

**Issue by iris2jane** [Snezhig/obsidian-meta-title-filename#1]
Can [BRAT](https://github.com/TfTHacker/obsidian42-brat) installation be supported?

Thanks for your great work 👏👏👏

**Comment by Snezhig** [comment]
It seems interesting. I will read about it.

**Comment by Snezhig** [comment]
As I understood, I just have to add manifest-beta.json and create beta-releases for plugin, until it's not ready for actual release?

**Comment by iris2jane** [comment]
Yeah, it can be installed now.
