### ISSUE TITLE
Switch off for filenames

### ISSUE THREAD

**Issue by Serzh470** [Snezhig/obsidian-meta-title-filename#2]
Hi!

Thanks for great plugin, it's definitely the right thins I've been searching.

I would like an feature - switch off toggle in settings for file names. I use zettelkasten id prefix and do not need filenames from yaml.

**Comment by Snezhig** [comment]
Hi. Do you want to use this plugin for graph only, but not for explorer?

**Comment by Serzh470** [comment]
Yes, may be later I'll make an PR for this, in my vault I've just comment explorer blocks now

**Comment by Snezhig** [comment]
I added option to do it yesterday.
