### ISSUE TITLE
Unable to enable the plugin in Obsidian

### ISSUE THREAD

**Issue by Exomancer** [Snezhig/obsidian-meta-title-filename#3]
Obdidian 1.2.0 (50) on Android

Downloaded the plugin from your Github.
Version 1.0.1 [58b4ad1]
commit 58b4ad10ceee87fb9fcf8dd90af518165233a94e

Opened the downloaded zip and copied the included folder to my vault .obsidian/plugins folder.

Renamed the folder by removing the "-master" from the end of the folder name (It made no difference if I renamed it or not. The problem remained either way). 

On trying to enable the plugin I get the error message "failed to load plugin obsidian-meta-title-filename-plugin".

Restarted Obsidian, same issue.  I can't get it to work.

**Comment by Snezhig** [comment]
Hi, I think that I have downloaded the zip with source code.
Check the [release](https://github.com/Snezhig/obsidian-meta-title-filename/releases/tag/1.0.1). I added zip archive with built code.

**Comment by Exomancer** [comment]
Thank you!  That fixed the problem.  This is an AWESOME plugin!

----------------------------------------

May 10, 2022 1:40:48 AM snezhig ***@***.***>:

**Comment by Snezhig** [comment]
Thank you. I will try to improve this plugin.
So, I close the issue.
